"""Allergy terminology definitions for CH AllergyIntolerance mapping."""

ALLERGY = {
    "CH_ALLERGY_INTOLERANCE_VALUESET": (
        "http://fhir.ch/ig/ch-term/ValueSet/CHAllergyIntoleranceValueSet"
    ),
    "CLINICAL_STATUS_SYSTEM": (
        "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical"
    ),
    "VERIFICATION_STATUS_SYSTEM": (
        "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification"
    ),
    "CRITICALITY_SYSTEM": (
        "http://hl7.org/fhir/allergy-intolerance-criticality"
    ),
    "REACTION_MANIFESTATION_SYSTEM": "http://snomed.info/sct",
    "CRITICALITY_HIGH_CDA_CODE": "CRITH",
    "CRITICALITY_LOW_CDA_CODE": "CRITL",
    "CRITICALITY_HIGH_FHIR_CODE": "high",
    "CRITICALITY_LOW_FHIR_CODE": "low",
    "ACTIVE_STATUS_CDA_CODE": "55561003",
    "ACTIVE_STATUS_FHIR_CODE": "active",
    "VERIFIED_STATUS_FHIR_CODE": "confirmed",
    "DEFAULT_ALLERGY_TEXT": "Allergy",
    "REACTION_TYPE_CODE": "418799008",
    "REACTION_TYPE_TEXT": "Symptom",
}

CH_ALLERGY_INTOLERANCE_VALUESET = ALLERGY["CH_ALLERGY_INTOLERANCE_VALUESET"]
CLINICAL_STATUS_SYSTEM = ALLERGY["CLINICAL_STATUS_SYSTEM"]
VERIFICATION_STATUS_SYSTEM = ALLERGY["VERIFICATION_STATUS_SYSTEM"]
CRITICALITY_SYSTEM = ALLERGY["CRITICALITY_SYSTEM"]
REACTION_MANIFESTATION_SYSTEM = ALLERGY["REACTION_MANIFESTATION_SYSTEM"]
CRITICALITY_HIGH_CDA_CODE = ALLERGY["CRITICALITY_HIGH_CDA_CODE"]
CRITICALITY_LOW_CDA_CODE = ALLERGY["CRITICALITY_LOW_CDA_CODE"]
CRITICALITY_HIGH_FHIR_CODE = ALLERGY["CRITICALITY_HIGH_FHIR_CODE"]
CRITICALITY_LOW_FHIR_CODE = ALLERGY["CRITICALITY_LOW_FHIR_CODE"]
ACTIVE_STATUS_CDA_CODE = ALLERGY["ACTIVE_STATUS_CDA_CODE"]
ACTIVE_STATUS_FHIR_CODE = ALLERGY["ACTIVE_STATUS_FHIR_CODE"]
VERIFIED_STATUS_FHIR_CODE = ALLERGY["VERIFIED_STATUS_FHIR_CODE"]
DEFAULT_ALLERGY_TEXT = ALLERGY["DEFAULT_ALLERGY_TEXT"]
REACTION_TYPE_CODE = ALLERGY["REACTION_TYPE_CODE"]
REACTION_TYPE_TEXT = ALLERGY["REACTION_TYPE_TEXT"]
